sudo: required

# Install Docker
servers:
  - docker

# Execite logic
script:
  - echo "Hello Students!"

after_success:
  # Build all the docker files
  - docker build -t swarajdhore/zomato-clone-client ./client
  - docker build -t swarajdhore/zomato-clone-server ./server
  - docker build -t swarajdhore/zomato-clone-nginx ./nginx

  # log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push swarajdhore/zomato-clone-client
  - docker push swarajdhore/zomato-clone-server
  - docker push swarajdhore/zomato-clone-nginx

deploy:
  # deploy to AWS EBS
  provider: elasticbeanstalk
  region: us-east-2
  app: zomato-clone-swarajdhore
  env: Zomatocloneswarajdhore-env
  bucket_name: elasticbeanstalk-us-east-2-383455786171
  bucket_path: zomatoclone
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET